---
resources:
- name: resource-app
  type: git
  source:
    uri: https://github.com/tonan/simple-java-maven-app.git
    branch: concourse

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-app
    trigger: true
  - task: web-app-test
    file: resource-app/tasks/run-unit-tests.yml

- name: job-build-app
  public: true
  plan:
  - get: resource-app
    trigger: true
    passed: [job-test-app]
  - task: web-app-build
    file: resource-app/tasks/build-app.yml
